<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Aion2FunDps.Capture\Aion2FunDps.Capture.csproj" />
    <ProjectReference Include="..\Aion2FunDps.Protocol\Aion2FunDps.Protocol.csproj" />
    <ProjectReference Include="..\Aion2FunDps.Core\Aion2FunDps.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
